name: chat_flutter_sdk
description: "Official Yalo Flutter chat SDK"
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  path: ^1.9.1
  clock: ^1.1.2
  mocktail: ^1.0.4
  equatable: ^2.0.7
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  record: ^6.1.2
  logging: ^1.3.0
  uuid: ^4.5.2
  audioplayers: ^6.5.1
  image_picker: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.26.2
  bloc_test: ^10.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.7.1

flutter:
  assets:
    - assets/images/
  plugin:
    platforms:
      android:
        package: ai.yalo.chat_flutter_sdk
        pluginClass: ChatFlutterSdkPlugin
      ios:
        pluginClass: ChatFlutterSdkPlugin
      web:
        pluginClass: ChatFlutterSdkWeb
        fileName: chat_flutter_sdk_web.dart
