name: chat_flutter_sdk
description: "Official Yalo Flutter chat SDK"
version: 0.0.2
homepage: https://github.com/yalochat/chat-sdk

environment:
  sdk: ^3.9.2
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  path: ^1.9.1
  clock: ^1.1.2
  mocktail: ^1.0.4
  equatable: ^2.0.7
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  record: ^6.1.2
  logging: ^1.3.0
  uuid: ^4.5.2
  audioplayers: ^6.5.1
  image_picker: ^1.2.1
  cross_file: ^0.3.5+1
  mime: ^2.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  json_annotation: ^4.9.0
  http: ^1.6.0
  flutter_markdown_plus: ^1.0.7
  ecache: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.26.2
  bloc_test: ^10.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.2

flutter:
  generate: true
