# Copyright (c) Yalochat, Inc. All rights reserved.

name: Flutter SDK Pipeline

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
    paths:
      - 'flutter-sdk/**'

  pull_request:

jobs:
  flutter-sdk-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter_sdk
    steps:
      - uses: actions/checkout@v5
      - name: Gitleaks Scan
        run: docker run --rm -v ${{ github.workspace }}:/code zricethezav/gitleaks:latest detect --source="/code" -v
      - name: Install LCOV
        run: sudo apt-get install -y lcov
      - name: Cache pub deps
        uses: actions/cache@v5
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-
      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Fetch deps
        run: flutter pub get
      - name: Flutter analyze/lint
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Remove coverage stats from codegen files
        run: lcov --remove coverage/lcov.info "lib/**/*.g.dart" -o coverage/lcov.info
      - name: Upload to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: flutter_sdk
