# This file was automatically created by the create repository workflow. 
# Please, DO NOT CHANGE the job names, since they are used to make sure our repos
# have a lint and test stages.

# Later, complete this workflow with the steps to lint and test your code.
# We recommend submitting test coverage to Codecov, and the unit test requirement
# will be automatically validated!
# Feel free to remove these comments when you're done.

# If you are using Go, you are encouraged to use the centralized workflow to perform
# these steps. You can find an usage example on the link below
# https://github.com/yalochat/salesdesk-api/blob/main/.github/workflows/build-and-test.yml

name: Lint and Test

on:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
