# Copyright (c) Yalochat, Inc. All rights

name: Test flutter SDK

on:
  push:
    branches:
      - *
    tags:
      - *.*.*
    paths:
      - 'flutter_sdk/**/*.dart'
jobs:
  test-flutter-sdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter_sdk
    steps:
      - uses: uses: actions/checkout@v5
      - name: Cache pub deps
        uses: actions/cache@v5
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-
      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Fetch deps
        run: flutter pub get
      - name: Run tests
        run: flutter test --coverage
      - name: Remove coverage stats from codegen files
        run: lcov --remove coverage/lcov.info "lib/**/*.g.dart" -o coverage/lcov.info
      - name: Upload to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
